# Use postgres/example user/password credentials
version: '3.1'

services:
  tibia_database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
    container_name: tibia_database

  tibia_caching:
    image: redis
    ports:
      - 63791:6379
    container_name: tibia_caching
